version: '2'

services:

  app:
    container_name: youtube-to-rss.app
    build: docker/php
    volumes:
      - .:/var/www

  nginx:
    container_name: youtube-to-rss.nginx
    build: docker/nginx
    volumes_from:
      - app
    ports:
      - 835:80
